### ISSUE TITLE
First try of documentation server, using "mkdocs serve" crashes

### ISSUE THREAD

**Issue by ph99** [matrix-io/matrix-documentation#108]
I am not particularly swift with Python, but the very, very first thing I tried was bringing up the documentation, and the instructions provided led to an immediate crash.

Followed instructions in README.md from matrix-documentation-master folder, for setting up docs server using Python. It immediately crashed.

I am using Python 3.7.6 - is this the problem? Does it require Python 2?

Here is the output:

(env) (base) paul@krill:~/matrix/matrix-documentation-master$ mkdocs serve
INFO    -  Building documentation... 
Traceback (most recent call last):
  File "/home/paul/matrix/matrix-documentation-master/env/lib/python3.7/site-packages/mkdocs/config/config_options.py", line 366, in walk_docs_dir
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/paul/matrix/matrix-documentation-master/env/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/home/paul/matrix/matrix-documentation-master/env/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/paul/matrix/matrix-documentation-master/env/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/paul/matrix/matrix-documentation-master/env/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/paul/matrix/matrix-documentation-master/env/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/paul/matrix/matrix-documentation-master/env/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/paul/matrix/matrix-documentation-master/env/lib/python3.7/site-packages/mkdocs/__main__.py", line 127, in serve_command
    livereload=livereload
  File "/home/paul/matrix/matrix-documentation-master/env/lib/python3.7/site-packages/mkdocs/commands/serve.py", line 110, in serve
    config = builder()
  File "/home/paul/matrix/matrix-documentation-master/env/lib/python3.7/site-packages/mkdocs/commands/serve.py", line 101, in builder
    theme_dir=theme_dir
  File "/home/paul/matrix/matrix-documentation-master/env/lib/python3.7/site-packages/mkdocs/config/base.py", line 181, in load_config
    errors, warnings = cfg.validate()
  File "/home/paul/matrix/matrix-documentation-master/env/lib/python3.7/site-packages/mkdocs/config/base.py", line 105, in validate
    post_failed, post_warnings = self._post_validate()
  File "/home/paul/matrix/matrix-documentation-master/env/lib/python3.7/site-packages/mkdocs/config/base.py", line 85, in _post_validate
    config_option.post_validation(self, key_name=key)
  File "/home/paul/matrix/matrix-documentation-master/env/lib/python3.7/site-packages/mkdocs/config/config_options.py", line 391, in post_validation
    for filename in self.walk_docs_dir(config['docs_dir']):
RuntimeError: generator raised StopIteration

**Comment by samreenislam** [comment]
Hi @ph99, you can access our documentation [here](https://docs.matrix.one) if you want to see a rendered version.

**Comment by AndresTFG** [comment]
"The URL is no longer available

**Comment by matrixplatform** [comment]
Hi Andres,

You can find the documentation here
https://github.com/matrix-io/matrix-documentation




*Alejandro Gutierrez*

7900 Oak Lane, Suite 400
Miami Lakes, FL 33016
Phone ( <(786)%20554-9987>954) 663-4497
www.matrixlabs.ai
